spring:
  application:
    name: service-log
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    template:
      default-topic: log-event-topic
    listener:
      concurrency: 5

server:
  port: 8090

cloud:
  aws:
    dynamodb:
      endpoint: http://localhost:4566
    credentials:
      access-key: admin
      secret-key: admin
    region:
      static: sa-east-1
